name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # Optional: outputs from the release please action
      - name: Show outputs
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          echo "Release created: ${{ steps.release.outputs.releases_created }}"
          echo "Tag name: ${{ steps.release.outputs.tag_name }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"
